apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nome }}
  labels:
    app: {{ .Values.nome }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.servico.porta }}
      targetPort: http
  selector:
    app: {{ .Values.nome }}
